version: '3.1'

services:
  db:
    image: mysql
    container_name: betsson-db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - container-volume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql 
    environment:
      MYSQL_DATABASE: betsson_api
      MYSQL_ROOT_PASSWORD: root
    networks:
      - betsson-network 
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: betsson-api
    working_dir: /var/www/html/betsson/
    volumes:
      - ./api:/var/www/html/betsson/
    networks:
      - betsson-network
  nginx:
    build: 
      context: .
      dockerfile: nginx/Dockerfile
    container_name: betsson-nginx
    restart: unless-stopped
    tty: true
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./api:/var/www/html/betsson/
    ports:
      - "8080:80"
    links:
      - api
    networks:
      - betsson-network
      

networks:
  betsson-network:
    driver: bridge

volumes:
  container-volume:
    
